
/* delete data in tables */
DELETE  FROM ASSIGNMENT;
DELETE  FROM EMPLOYEE;
DELETE  FROM DEPARTMENT;
DELETE  FROM PROJECT;

/* delete tables */
DROP TABLE ASSIGNMENT;
DROP TABLE PROJECT;
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;


